name: sewashubham-api
region: blr
services:
  - name: api
    github:
      repo: ayushrathore1/sewashubhambackery
      branch: main
      deploy_on_push: true
    source_dir: /backend
    http_port: 5000
    instance_count: 1
    instance_size_slug: basic-xs
    routes:
      - path: /
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        type: SECRET
      - key: JWT_SECRET  
        type: SECRET
      - key: ALLOWED_ORIGINS
        value: "${APP_URL}"
      - key: CLOUDINARY_CLOUD_NAME
        type: SECRET
      - key: CLOUDINARY_API_KEY
        type: SECRET
      - key: CLOUDINARY_API_SECRET
        type: SECRET
      - key: RAZORPAY_KEY_ID
        type: SECRET
      - key: RAZORPAY_KEY_SECRET
        type: SECRET
